"""Phase 2 - working hours, recurring exceptions

Revision ID: 5ab497d5b544
Revises: 001
Create Date: 2026-03-11 10:48:43.271374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab497d5b544'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_event_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('new_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recur_exceptions_event_date', 'recurring_event_exceptions', ['event_id', 'exception_date'], unique=False)
    op.add_column('users', sa.Column('working_hours_start', sa.Integer(), nullable=False, server_default='9'))
    op.add_column('users', sa.Column('working_hours_end', sa.Integer(), nullable=False, server_default='18'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'working_hours_end')
    op.drop_column('users', 'working_hours_start')
    op.drop_index('ix_recur_exceptions_event_date', table_name='recurring_event_exceptions')
    op.drop_table('recurring_event_exceptions')
    # ### end Alembic commands ###
